<?php

/**
 * @file
 * Contains shipboard_services.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shipboard_services_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shipboard_services module.
    case 'help.page.shipboard_services':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration with the Shipboard API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function shipboard_services_theme() {
  return [
    'shipboard_services' => [
      'render element' => 'children',
    ],
  ];
}
